env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'airbnb-typescript'
  - 'next/core-web-vitals'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: 'module'
  project: ['tsconfig.json']
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'jsx-a11y'
  - 'react'
  - 'react-hooks'
rules:
  # ---------------------------------- Eslint ---------------------------------- #
  arrow-body-style: [1, 'as-needed']
  # ---------------------------------- Import ---------------------------------- #
  import/no-named-export: 0
  import/prefer-default-export: 0
  # ----------------------------------- React ---------------------------------- #
  react/function-component-definition: [2, {namedComponents: 'arrow-function', unnamedComponents: 'arrow-function'}]
  react/jsx-fragments: [2, 'element']
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/require-default-props: 0
