import {Company} from '@prisma/client';

export const companies: Company[] = [
  {
    id: '63893f797fe7d05cd13c5bbf',
    logoBackgroundColor: '#ea9310',
    logoUrl: `https://drive.google.com/u/2/uc?id=1n7AQV0TyqQipG8j0UBER_06IP8f-AUBG&export=download`,
    name: 'Scoot',
    websiteUrl: 'https://example.com/scoot',
  },
  {
    id: '638afbb1140d24a2f4622979',
    logoBackgroundColor: '#e54b24',
    logoUrl: `https://drive.google.com/u/2/uc?id=1b3zBSXNoZj7Y6OIDdkzJUkO_AXoVVvDQ&export=download`,
    name: 'Blogr',
    websiteUrl: 'https://example.com/blogr',
  },
  {
    id: '638b094c3cc5f6d2d08eb9da',
    logoBackgroundColor: '#353641',
    logoUrl: `https://drive.google.com/u/2/uc?id=15AJ9H57IRCCAl-XPfU9OgqxZnVaYvom-&export=download`,
    name: 'Vector',
    websiteUrl: 'https://example.com/vector',
  },
  {
    id: '638b379dfc652c1a1f18e9db',
    logoBackgroundColor: '#2f4fc6',
    logoUrl: `https://drive.google.com/u/2/uc?id=1uxwynusyG9AF2D6UTQOxy5O9YOi0krLC&export=download`,
    name: 'Office Lite',
    websiteUrl: 'https://example.com/office-lite',
  },
  {
    id: '638b3bb3f868816e2b7f303d',
    logoBackgroundColor: '#132034',
    logoUrl: `https://drive.google.com/u/2/uc?id=1rEU22GAwiCTBcWtUeDdUxzlFiSTSLUwf&export=download`,
    name: 'Pod',
    websiteUrl: 'https://example.com/pod',
  },
  {
    id: '638b3e06e687b92e5a7d33ce',
    logoBackgroundColor: '#4e1853',
    logoUrl: `https://drive.google.com/u/2/uc?id=1Fkd-Cmyf7Nn0DEZ_LRak5zOcjlM5kGku&export=download`,
    name: 'Creative',
    websiteUrl: 'https://example.com/creative',
  },
  {
    id: '638b3f6baf3a0472cff7ac3a',
    logoBackgroundColor: '#4721c4',
    logoUrl: `https://drive.google.com/u/2/uc?id=1DGd6bZCZCpSp-fK_fpUck87xytvL1jZn&export=download`,
    name: 'Pomodoro',
    websiteUrl: 'https://example.com/pomodoro',
  },
  {
    id: '639150ccb0a6a292ca04f637',
    logoBackgroundColor: '#21437d',
    logoUrl: `https://drive.google.com/u/2/uc?id=1ujmYZm-1OUoW5oiIEGuMODlnbKt8Xuuo&export=download`,
    name: 'Maker',
    websiteUrl: 'https://example.com/maker',
  },
  {
    id: '6391520c02e4fa0ce5cb9fee',
    logoBackgroundColor: '#f2ddca',
    logoUrl: `https://drive.google.com/u/2/uc?id=15vFyqHf_HIscmWCLrxzoPzja1V5XGTet&export=download`,
    name: 'Coffeeroasters',
    websiteUrl: 'https://example.com/coffeeroasters',
  },
  {
    id: '639152f4c2a5bb0765a09b6a',
    logoBackgroundColor: '#1f1f1f',
    logoUrl: `https://drive.google.com/u/2/uc?id=1YNUQ7p9JVayjOVVAy2b_MV0V4L59ihuA&export=download`,
    name: 'Mastercraft',
    websiteUrl: 'https://example.com/mastercraft',
  },
  {
    id: '6391546d3a97469c2cbf5401',
    logoBackgroundColor: '#37c890',
    logoUrl: `https://drive.google.com/u/2/uc?id=17q0Wb_PtchY2g_EddLJDT4D8seJN3l4f&export=download`,
    name: 'Crowdfund',
    websiteUrl: 'https://example.com/crowdfund',
  },
  {
    id: '6391554da7ba84f45bfb7541',
    logoBackgroundColor: '#f26818',
    logoUrl: `https://drive.google.com/u/2/uc?id=1WsrBayKxzu_BpuQMPM97zOkERXtkVweI&export=download`,
    name: 'Typemaster',
    websiteUrl: 'https://example.com/typemaster',
  },
];
