export const defaultJobs = [
  {
    company: 'Photosnap',
    contract: 'Full Time',
    id: 1,
    isFeatured: true,
    isNew: true,
    location: 'USA only',
    logoPath: 'svgs/logo-photosnap.svg',
    position: 'Senior Frontend Developer',
    postedAt: '1d ago',
    tags: ['Frontend', 'Senior', 'HTML', 'CSS', 'JavaScript'],
  },
  {
    company: 'Manage',
    contract: 'Part Time',
    id: 2,
    isFeatured: true,
    isNew: true,
    location: 'Remote',
    logoPath: 'svgs/logo-manage.svg',
    position: 'Fullstack Developer',
    postedAt: '1d ago',
    tags: ['Fullstack', 'Midweight', 'Python', 'React'],
  },
  {
    company: 'Account',
    contract: 'Part Time',
    id: 3,
    isFeatured: false,
    isNew: true,
    location: 'USA only',
    logoPath: 'svgs/logo-account.svg',
    position: 'Junior Frontend Developer',
    postedAt: '2d ago',
    tags: ['Frontend', 'Junior', 'React', 'Sass', 'JavaScript'],
  },
  {
    company: 'MyHome',
    contract: 'Contract',
    id: 4,
    isFeatured: false,
    isNew: false,
    location: 'USA only',
    logoPath: 'svgs/logo-myhome.svg',
    position: 'Junior Frontend Developer',
    postedAt: '5d ago',
    tags: ['Frontend', 'Junior', 'CSS', 'JavaScript'],
  },
  {
    company: 'Loop Studios',
    contract: 'Full Time',
    id: 5,
    isFeatured: false,
    isNew: false,
    location: 'Worldwide',
    logoPath: 'svgs/logo-loop-studios.svg',
    position: 'Software Engineer',
    postedAt: '1w ago',
    tags: ['Fullstack', 'Midweight', 'JavaScript', 'Ruby', 'Sass'],
  },
  {
    company: 'FaceIt',
    contract: 'Full Time',
    id: 6,
    isFeatured: false,
    isNew: false,
    location: 'UK only',
    logoPath: 'svgs/logo-faceit.svg',
    position: 'Junior Backend Developer',
    postedAt: '2w ago',
    tags: ['Backend', 'Junior', 'Ruby', 'RoR'],
  },
  {
    company: 'Shortly',
    contract: 'Full Time',
    id: 7,
    isFeatured: false,
    isNew: false,
    location: 'Worldwide',
    logoPath: 'svgs/logo-shortly.svg',
    position: 'Junior Developer',
    postedAt: '2w ago',
    tags: ['Frontend', 'Junior', 'HTML', 'Sass', 'JavaScript'],
  },
  {
    company: 'Insure',
    contract: 'Full Time',
    id: 8,
    isFeatured: false,
    isNew: false,
    location: 'USA only',
    logoPath: 'svgs/logo-insure.svg',
    position: 'Junior Frontend Developer',
    postedAt: '2w ago',
    tags: ['Frontend', 'Junior', 'Vue', 'JavaScript', 'Sass'],
  },
  {
    company: 'Eyecam Co.',
    contract: 'Full Time',
    id: 9,
    isFeatured: false,
    isNew: false,
    location: 'Worldwide',
    logoPath: 'svgs/logo-eyecam-co.svg',
    position: 'Full Stack Engineer',
    postedAt: '3w ago',
    tags: ['Fullstack', 'Midweight', 'JavaScript', 'Django', 'Python'],
  },
  {
    company: 'The Air Filter Company',
    contract: 'Part Time',
    id: 10,
    isFeatured: false,
    isNew: false,
    location: 'Worldwide',
    logoPath: 'svgs/logo-the-air-filter-company.svg',
    position: 'Front-end Dev',
    postedAt: '1mo ago',
    tags: ['Frontend', 'Junior', 'React', 'Sass', 'JavaScript'],
  },
];
